#!/usr/bin/env bash
## Lookup "nixpkg.name" using a "pname" (e.g. "gnome-shell" -> "nixpkgs.gnome.gnome-shell")
## Usage: nixpkg-name PNAME
set -u

dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
dim='\e[2m'
reset='\e[0m'

# TODO escape regex chars? may not need to...
if ! matches=$(rg " $1(-.*)?$" "$dir"/.search-index.txt | cut -d' ' -f1); then
    echo "No nixpkg name found for $1" >&2
    exit 1
fi

n_matches=$(echo "$matches" | wc -l)
if [ "$n_matches" -gt 1 ]; then
    shortest_match=$(echo "$matches" | awk '{ print length, $0 }' | sort -n | cut -d' ' -f2 | head -n1)
    echo -e "${dim}Warning: '$1' matches $n_matches nixpkg names. Picking shortest ($shortest_match)$reset" >&2
    echo "$shortest_match"
else
    echo "$matches"
fi
