#!/usr/bin/env bash
## Search through available packages
## Usage: search [--refresh] PACKAGE_REGEX
set -euo pipefail

dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ "${1:-}" == "--refresh" ]] || [ ! -f "$dir/.search-index.txt" ]; then
    echo "Refreshing packages..." >&2
    # Uses a lot of ram, check if at least 3G of ram available
    available_ram_g=$(free -g | rg '^Mem' | tr -s ' ' | cut -d' ' -f7)
    if [ "$available_ram_g" -lt 3 ]; then
        echo "Error: Insufficient available ram (${available_ram_g}G < 3G)" >&2
        exit 1
    fi

    nix-env -qaP > "$dir/.search-index.txt"
    wc -l "$dir/.search-index.txt"
    shift
    if [ -z "${1:-}" ]; then exit; fi
fi

if ! rg --color=always -N "^nixpkgs\.$1" "$dir/.search-index.txt" | sed -E 's/\s+/ = /'; then
    rg --color=always -N "$1" "$dir/.search-index.txt" | sed -E 's/\s+/ = /'
fi
