#!/usr/bin/env bash
## Search through available packages
## Usage: search [--refresh]
set -euo pipefail

dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ "${1:-}" == "--refresh" ]]; then
    echo "Refreshing packages..." >&2
    nix-env -qaP | cut -d' ' -f1 > "$dir/.search-index.txt"
    wc -l "$dir/.search-index.txt"
    shift
    if [ -z "${1:-}" ]; then exit; fi
fi

if ! rg -N "^nixpkgs\.$1" "$dir/.search-index.txt"; then
    rg -N "$1" "$dir/.search-index.txt"
fi
