#!/usr/bin/env bash
## Updates all installed packages.
## Usage: update [--check]
set -euo pipefail

dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
bold='\e[1m'
dim='\e[2m'
reset='\e[0m'

print_current() {
    echo 'with import <nixpkgs> {}; ['
    nix-env -q --json | jq -r '.[] | .pname' \
        | xargs -P3 -n1 "$dir/nixpkg-name" \
        | sed 's/^nixpkgs./  /' \
        | sort
    echo ']'
}

echo -e "$bold==> nix-channel --update$reset"
nix-channel --update

echo -e "$bold==> checking for updates$reset"
current=$(mktemp)
trap 'rm -f "$current"' EXIT

print_current > "$current"
current_v=$(nix-env -qaf "$current")

updates=$(diff --suppress-common-lines --side-by-side <(echo "$current_v") <(nix-env -q) \
            | sed -E 's#\s*\|\s*#  ->  #' \
            || true)

if [ -z "$updates" ]; then
    echo "no updates"
    exit
else
    echo "------"
    echo "$updates"
    echo "------"
fi

if [ -z "${1:-}" ]; then
    echo -e "$bold==> installing updates$reset"
    nix-env -irf "$current"
else
    echo -e "${dim}Run without args to install updates$reset"
    exit
fi
